### PR TITLE
add README and text to homepage

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by Spomky** [comment]
Thanks.
I close because alrady changed in the last commit

**Comment by Spomky** [comment]
Looks good.
Unfortunately I cannot resolve the conflit. I will merge when done.

**Comment by tacman** [comment]
oh, drat, I hadn't meant for that last commit to get in the PR, I forgot to create another branch.  

It's somewhat specific to my dokku setup (app.json and nginx.conf for example).

**Comment by Spomky** [comment]
😅Just tell me when its ready and I will merge.
Having extra files is not an issue. I use Heroku that uses similar configuration files.
One question though: why did you renamed [Dockerfile → Dockerfile.sav](https://github.com/Spomky-Labs/phpwa-demo/pull/3/files#diff-17959b1bda59852643f2b388e68b79fe8d1c8d053f17060f56097630acf72adf)?

**Comment by Spomky** [comment]
> When I pushed to dokku, it tried to build the Dockerfile (and failed, as it did for me locally). Since I was thinking I was on my own branch, I simply renamed it.
Ok. Understood.

> Do you have a paid account at Heroku?
Yes. Some of my customers have applications running on it. It is not only expensive for a demo, but also for running apps...
I migrated most of them to Docker with Digital Ocean or a Jelastic instance.

**Pull request merged**
